<a href="https://colab.research.google.com/github/sreeakhil47/E-Commerce-Data-Pipeline-Analytics-Platform/blob/main/Cleaned_Datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Installation Of Python Libraries

In [ ]:
import pandas as pd
import numpy as np
from pathlib import Path

print("Pandas version:", pd.__version__)
print("Setup completed!")

Pandas version: 2.2.3
Setup completed!

# 2. Checking The Loaded Datasets

In [ ]:
from pathlib import Path
import pandas as pd

RAW_DIR = Path("/content/raw_data")

datasets = {}

for file in RAW_DIR.glob("*.csv"):
    name = file.stem.lower()
    datasets[name] = pd.read_csv(file)

print("Datasets loaded:", list(datasets.keys()))

Datasets loaded: ['sellers', 'customers', 'products', 'analytics', 'reviews', 'payments', 'orders', 'order_items']

# 3. A Sample Check For The Dataset customers.csv

In [ ]:
customers = datasets["customers"]

display(customers.head())
print("Shape:", customers.shape)

,customer_id,customer_name,gender,age,city,state,registration_date
0,CUST0001,Customer 1,Female,33,Vijayawada,Andhra Pradesh,2024-08-16
1,CUST0002,Customer 2,Male,52,Mangaluru,Karnataka,2024-03-30
2,CUST0003,Customer 3,Male,31,Ahmedabad,Gujarat,2024-08-26
3,CUST0004,Customer 4,Male,59,Nizamabad,Telangana,2025-12-19
4,CUST0005,Customer 5,Male,35,Ahmedabad,Gujarat,2024-01-07

Shape: (300, 7)

# 4. Understanding The Datasets Before Cleaning

In [ ]:
for name, df in datasets.items():
    print("\n" + "=" * 50)
    print("DATASET:", name.upper())
    print("=" * 50)

    print("Rows and columns:", df.shape)
    print("\nColumn names:")
    print(df.columns.tolist())

    print("\nData types:")
    print(df.dtypes)

    print("\nFirst five rows:")
    display(df.head())

==================================================
DATASET: SELLERS
==================================================
Rows and columns: (40, 5)

Column names:
['seller_id', 'seller_name', 'city', 'state', 'seller_rating']

Data types:
seller_id         object
seller_name       object
city              object
state             object
seller_rating    float64
dtype: object

First five rows:

  seller_id seller_name       city           state  seller_rating
0   SELL001    Seller 1   Tirupati  Andhra Pradesh            4.5
1   SELL002    Seller 2  Bengaluru       Karnataka            4.5
2   SELL003    Seller 3  New Delhi           Delhi            4.7
3   SELL004    Seller 4  Hyderabad       Telangana            3.6
4   SELL005    Seller 5     Nagpur     Maharashtra            3.8

==================================================
DATASET: CUSTOMERS
==================================================
Rows and columns: (300, 7)

Column names:
['customer_id', 'customer_name', 'gender', 'age', 'city', 'state', 'registration_date']

Data types:
customer_id          object
customer_name        object
gender               object
age                   int64
city                 object
state                object
registration_date    object
dtype: object

First five rows:

,customer_id,customer_name,gender,age,city,state,registration_date
0,CUST0001,Customer 1,Female,33,Vijayawada,Andhra Pradesh,2024-08-16
1,CUST0002,Customer 2,Male,52,Mangaluru,Karnataka,2024-03-30
2,CUST0003,Customer 3,Male,31,Ahmedabad,Gujarat,2024-08-26
3,CUST0004,Customer 4,Male,59,Nizamabad,Telangana,2025-12-19
4,CUST0005,Customer 5,Male,35,Ahmedabad,Gujarat,2024-01-07

==================================================
DATASET: PRODUCTS
==================================================
Rows and columns: (100, 6)

Column names:
['product_id', 'product_name', 'category', 'subcategory', 'unit_price', 'cost_price']

Data types:
product_id       object
product_name     object
category         object
subcategory      object
unit_price      float64
cost_price      float64
dtype: object

First five rows:

,product_id,product_name,category,subcategory,unit_price,cost_price
0,PROD0001,Audio Product 1,Electronics,Audio,25490.01,16155.83
1,PROD0002,Skincare Product 2,Beauty,Skincare,3080.28,2385.86
2,PROD0003,Smartphones Product 3,Electronics,Smartphones,30846.67,21188.83
3,PROD0004,Makeup Product 4,Beauty,Makeup,27827.24,21254.19
4,PROD0005,Accessories Product 5,Electronics,Accessories,45475.24,32030.36

==================================================
DATASET: ANALYTICS
==================================================
Rows and columns: (2857, 21)

Column names:
['order_id', 'order_date', 'order_status', 'customer_id', 'gender', 'city', 'state', 'product_id', 'product_name', 'category', 'subcategory', 'quantity', 'selling_price', 'discount_percent', 'revenue', 'profit', 'freight_value', 'seller_id', 'seller_status_ref', 'seller_rating', 'delivery_days']

Data types:
order_id              object
order_date            object
order_status          object
customer_id           object
gender                object
city                  object
state                 object
product_id            object
product_name          object
category              object
subcategory           object
quantity               int64
selling_price        float64
discount_percent       int64
revenue              float64
profit               float64
freight_value        float64
seller_id             object
seller_status_ref     object
seller_rating        float64
delivery_days        float64
dtype: object

First five rows:

,order_id,order_date,order_status,customer_id,gender,city,state,product_id,product_name,category,...,quantity,selling_price,discount_percent,revenue,profit,freight_value,seller_id,seller_status_ref,seller_rating,delivery_days
0,ORD00001,2025-03-25 12:00:00,Returned,CUST0164,Male,Madurai,Tamil Nadu,PROD0066,Haircare Product 66,Beauty,...,1,43922.73,5,43922.73,12011.51,253.20,SELL035,SELL035,4.6,NaN
1,ORD00002,2025-06-07 23:00:00,Processing,CUST0299,Male,New Delhi,Delhi,PROD0084,Skincare Product 84,Beauty,...,1,40463.35,10,40463.35,10332.54,304.26,SELL038,SELL038,4.3,NaN
2,ORD00003,2025-12-15 07:00:00,Delivered,CUST0076,Male,Mysuru,Karnataka,PROD0041,Accessories Product 41,Fashion,...,1,31391.62,10,31391.62,10900.77,222.88,SELL027,SELL027,3.7,4.0
3,ORD00004,2025-12-28 04:00:00,Delivered,CUST0032,Female,Vijayawada,Andhra Pradesh,PROD0049,Skincare Product 49,Beauty,...,3,29294.94,5,87884.82,30995.37,280.57,SELL021,SELL021,4.2,5.0
4,ORD00005,2025-04-09 07:00:00,Delivered,CUST0248,Male,Mumbai,Maharashtra,PROD0099,Men Product 99,Fashion,...,1,12717.61,0,12717.61,3542.29,468.84,SELL032,SELL032,3.9,4.0

==================================================
DATASET: REVIEWS
==================================================
Rows and columns: (1452, 6)

Column names:
['review_id', 'order_id', 'customer_id', 'rating', 'sentiment', 'review_date']

Data types:
review_id      object
order_id       object
customer_id    object
rating          int64
sentiment      object
review_date    object
dtype: object

First five rows:

  review_id  order_id customer_id  rating sentiment review_date
0  REV00001  ORD00001    CUST0164       2  Negative  2025-04-09
1  REV00002  ORD00002    CUST0299       4  Positive  2025-06-21
2  REV00003  ORD00004    CUST0032       5  Positive  2026-01-07
3  REV00004  ORD00005    CUST0248       5  Positive  2025-04-17
4  REV00005  ORD00006    CUST0104       4  Positive  2025-10-20

==================================================
DATASET: PAYMENTS
==================================================
Rows and columns: (2000, 5)

Column names:
['payment_id', 'order_id', 'payment_method', 'payment_amount', 'payment_status']

Data types:
payment_id         object
order_id           object
payment_method     object
payment_amount    float64
payment_status     object
dtype: object

First five rows:

  payment_id  order_id    payment_method  payment_amount payment_status
0   PAY00001  ORD00001        Debit Card        43924.39           Paid
1   PAY00002  ORD00002        Debit Card        40480.40           Paid
2   PAY00003  ORD00003  Cash on Delivery        31469.12           Paid
3   PAY00004  ORD00004       Credit Card        87939.45           Paid
4   PAY00005  ORD00005               UPI       127907.10           Paid

==================================================
DATASET: ORDERS
==================================================
Rows and columns: (2000, 6)

Column names:
['order_id', 'customer_id', 'order_date', 'order_status', 'payment_method', 'shipping_state']

Data types:
order_id          object
customer_id       object
order_date        object
order_status      object
payment_method    object
shipping_state    object
dtype: object

First five rows:

,order_id,customer_id,order_date,order_status,payment_method,shipping_state
0,ORD00001,CUST0164,2025-03-25 12:00:00,Returned,Debit Card,Tamil Nadu
1,ORD00002,CUST0299,2025-06-07 23:00:00,Processing,Debit Card,Delhi
2,ORD00003,CUST0076,2025-12-15 07:00:00,Delivered,Cash on Delivery,Karnataka
3,ORD00004,CUST0032,2025-12-28 04:00:00,Delivered,Credit Card,Andhra Pradesh
4,ORD00005,CUST0248,2025-04-09 07:00:00,Delivered,UPI,Maharashtra

==================================================
DATASET: ORDER_ITEMS
==================================================
Rows and columns: (2857, 9)

Column names:
['order_id', 'order_item_id', 'product_id', 'seller_id', 'quantity', 'selling_price', 'discount_percent', 'item_revenue', 'freight_value']

Data types:
order_id             object
order_item_id         int64
product_id           object
seller_id            object
quantity              int64
selling_price       float64
discount_percent      int64
item_revenue        float64
freight_value       float64
dtype: object

First five rows:

,order_id,order_item_id,product_id,seller_id,quantity,selling_price,discount_percent,item_revenue,freight_value
0,ORD00001,1,PROD0066,SELL035,1,43922.73,5,43922.73,253.20
1,ORD00002,1,PROD0084,SELL038,1,40463.35,10,40463.35,304.26
2,ORD00003,1,PROD0041,SELL027,1,31391.62,10,31391.62,222.88
3,ORD00004,1,PROD0049,SELL021,3,29294.94,5,87884.82,280.57
4,ORD00005,1,PROD0099,SELL032,1,12717.61,0,12717.61,468.84

# 5. Checking For Missing Values

In [ ]:
for name, df in datasets.items():
    print(f"\n{name.upper()}")
    print(df.isnull().sum())

SELLERS
seller_id        0
seller_name      0
city             0
state            0
seller_rating    0
dtype: int64

CUSTOMERS
customer_id          0
customer_name        0
gender               0
age                  0
city                 0
state                0
registration_date    0
dtype: int64

PRODUCTS
product_id      0
product_name    0
category        0
subcategory     0
unit_price      0
cost_price      0
dtype: int64

ANALYTICS
order_id               0
order_date             0
order_status           0
customer_id            0
gender                 0
city                   0
state                  0
product_id             0
product_name           0
category               0
subcategory            0
quantity               0
selling_price          0
discount_percent       0
revenue                0
profit                 0
freight_value          0
seller_id              0
seller_status_ref      0
seller_rating          0
delivery_days        714
dtype: int64

REVIEWS
review_id      0
order_id       0
customer_id    0
rating         0
sentiment      0
review_date    0
dtype: int64

PAYMENTS
payment_id        0
order_id          0
payment_method    0
payment_amount    0
payment_status    0
dtype: int64

ORDERS
order_id          0
customer_id       0
order_date        0
order_status      0
payment_method    0
shipping_state    0
dtype: int64

ORDER_ITEMS
order_id            0
order_item_id       0
product_id          0
seller_id           0
quantity            0
selling_price       0
discount_percent    0
item_revenue        0
freight_value       0
dtype: int64

# 6. Percentage Of The Missing Values

In [ ]:
for name, df in datasets.items():
    missing = pd.DataFrame({
        "Missing_Count": df.isna().sum(),
        "Missing_Percentage": (
            df.isna().mean() * 100
        ).round(2)
    })

    print(f"\n{name.upper()}")
    display(missing[missing["Missing_Count"] > 0])

SELLERS

Empty DataFrame
Columns: [Missing_Count, Missing_Percentage]
Index: []

CUSTOMERS

Empty DataFrame
Columns: [Missing_Count, Missing_Percentage]
Index: []

PRODUCTS

Empty DataFrame
Columns: [Missing_Count, Missing_Percentage]
Index: []

ANALYTICS

               Missing_Count  Missing_Percentage
delivery_days            714               24.99

REVIEWS

Empty DataFrame
Columns: [Missing_Count, Missing_Percentage]
Index: []

PAYMENTS

Empty DataFrame
Columns: [Missing_Count, Missing_Percentage]
Index: []

ORDERS

Empty DataFrame
Columns: [Missing_Count, Missing_Percentage]
Index: []

ORDER_ITEMS

Empty DataFrame
Columns: [Missing_Count, Missing_Percentage]
Index: []

# **7. Replacing The Missing Values For analytics.csv File**

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving analytics.csv to analytics (1).csv

In [ ]:
import pandas as pd

# Get the actual uploaded filename
filename = next(iter(uploaded))

# Load the dataset
analytics_df = pd.read_csv(filename)

print("Dataset loaded successfully!")
print("File name:", filename)
print("Dataset shape:", analytics_df.shape)
print("Missing cells:", analytics_df.isna().sum().sum())

display(analytics_df.head())

Dataset loaded successfully!
File name: analytics (1).csv
Dataset shape: (2857, 21)
Missing cells: 714

,order_id,order_date,order_status,customer_id,gender,city,state,product_id,product_name,category,...,quantity,selling_price,discount_percent,revenue,profit,freight_value,seller_id,seller_status_ref,seller_rating,delivery_days
0,ORD00001,2025-03-25 12:00:00,Returned,CUST0164,Male,Madurai,Tamil Nadu,PROD0066,Haircare Product 66,Beauty,...,1,43922.73,5,43922.73,12011.51,253.20,SELL035,SELL035,4.6,NaN
1,ORD00002,2025-06-07 23:00:00,Processing,CUST0299,Male,New Delhi,Delhi,PROD0084,Skincare Product 84,Beauty,...,1,40463.35,10,40463.35,10332.54,304.26,SELL038,SELL038,4.3,NaN
2,ORD00003,2025-12-15 07:00:00,Delivered,CUST0076,Male,Mysuru,Karnataka,PROD0041,Accessories Product 41,Fashion,...,1,31391.62,10,31391.62,10900.77,222.88,SELL027,SELL027,3.7,4.0
3,ORD00004,2025-12-28 04:00:00,Delivered,CUST0032,Female,Vijayawada,Andhra Pradesh,PROD0049,Skincare Product 49,Beauty,...,3,29294.94,5,87884.82,30995.37,280.57,SELL021,SELL021,4.2,5.0
4,ORD00005,2025-04-09 07:00:00,Delivered,CUST0248,Male,Mumbai,Maharashtra,PROD0099,Men Product 99,Fashion,...,1,12717.61,0,12717.61,3542.29,468.84,SELL032,SELL032,3.9,4.0

In [ ]:
analytics_df = analytics_df.fillna("N/A")

print("Missing cells remaining:",
      analytics_df.isna().sum().sum())

display(analytics_df.head())

Missing cells remaining: 0

,order_id,order_date,order_status,customer_id,gender,city,state,product_id,product_name,category,...,quantity,selling_price,discount_percent,revenue,profit,freight_value,seller_id,seller_status_ref,seller_rating,delivery_days
0,ORD00001,2025-03-25 12:00:00,Returned,CUST0164,Male,Madurai,Tamil Nadu,PROD0066,Haircare Product 66,Beauty,...,1,43922.73,5,43922.73,12011.51,253.20,SELL035,SELL035,4.6,N/A
1,ORD00002,2025-06-07 23:00:00,Processing,CUST0299,Male,New Delhi,Delhi,PROD0084,Skincare Product 84,Beauty,...,1,40463.35,10,40463.35,10332.54,304.26,SELL038,SELL038,4.3,N/A
2,ORD00003,2025-12-15 07:00:00,Delivered,CUST0076,Male,Mysuru,Karnataka,PROD0041,Accessories Product 41,Fashion,...,1,31391.62,10,31391.62,10900.77,222.88,SELL027,SELL027,3.7,4.0
3,ORD00004,2025-12-28 04:00:00,Delivered,CUST0032,Female,Vijayawada,Andhra Pradesh,PROD0049,Skincare Product 49,Beauty,...,3,29294.94,5,87884.82,30995.37,280.57,SELL021,SELL021,4.2,5.0
4,ORD00005,2025-04-09 07:00:00,Delivered,CUST0248,Male,Mumbai,Maharashtra,PROD0099,Men Product 99,Fashion,...,1,12717.61,0,12717.61,3542.29,468.84,SELL032,SELL032,3.9,4.0

In [ ]:
analytics_df.to_csv(
    "analytics_cleaned.csv",
    index=False
)

from google.colab import files
files.download("analytics_cleaned.csv")

# 8. Quality Check For the Updated analytics.csv File

In [ ]:
import pandas as pd

analytics_df = pd.read_csv(
    "/content/analytics_cleaned.csv",
    keep_default_na=False
)

print("Missing cells:", analytics_df.isna().sum().sum())
print("Cells containing N/A:", (analytics_df == "N/A").sum().sum())
print("Cells containing NA:", (analytics_df == "NA").sum().sum())

Missing cells: 0
Cells containing N/A: 714
Cells containing NA: 0

In [ ]:
analytics_df = pd.read_csv(
    "/content/analytics_cleaned.csv",
    keep_default_na=False
)

missing_count = analytics_df.isna().sum().sum()

print("Final missing cell count:", missing_count)

Final missing cell count: 0

In [ ]:
print(analytics_df.isna().sum())

order_id             0
order_date           0
order_status         0
customer_id          0
gender               0
city                 0
state                0
product_id           0
product_name         0
category             0
subcategory          0
quantity             0
selling_price        0
discount_percent     0
revenue              0
profit               0
freight_value        0
seller_id            0
seller_status_ref    0
seller_rating        0
delivery_days        0
dtype: int64

# 9. Removing The Duplicate Values

In [ ]:
for name, df in datasets.items():
    print(name, "duplicate rows:", df.duplicated().sum())

customers_(1) duplicate rows: 0
analytics_cleaned_(1) duplicate rows: 0
sellers duplicate rows: 0
orders_(1) duplicate rows: 0
analytics_(1) duplicate rows: 0
customers duplicate rows: 0
analytics_cleaned_(3) duplicate rows: 0
order_items_(1) duplicate rows: 0
reviews_(1) duplicate rows: 0
analytics_quality_report duplicate rows: 0
analytics_cleaned_(2) duplicate rows: 0
customers_(2) duplicate rows: 0
sellers_(1) duplicate rows: 0
products duplicate rows: 0
products_(1) duplicate rows: 0
analytics duplicate rows: 0
reviews duplicate rows: 0
payments_(1) duplicate rows: 0
data_quality_report duplicate rows: 0
payments duplicate rows: 0
relationship_validation_report duplicate rows: 0
orders duplicate rows: 0
order_items duplicate rows: 0

# 10. Standardize Column Names And Text

In [ ]:
def standardize_columns(df):
    df = df.copy()

    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(r"[^a-z0-9]+", "_", regex=True)
        .str.strip("_")
    )

    return df

In [ ]:
datasets = {
    name: standardize_columns(df)
    for name, df in datasets.items()
}

print(datasets["customers"].columns.tolist())

['customer_id', 'customer_name', 'gender', 'age', 'city', 'state', 'registration_date']

In [ ]:
datasets = {
    name: standardize_columns(df)
    for name, df in datasets.items()
}

print(datasets["orders"].columns.tolist())

['order_id', 'customer_id', 'order_date', 'order_status', 'payment_method', 'shipping_state']

In [ ]:
datasets = {
    name: standardize_columns(df)
    for name, df in datasets.items()
}

print(datasets["sellers"].columns.tolist())

['seller_id', 'seller_name', 'city', 'state', 'seller_rating']

In [ ]:
datasets = {
    name: standardize_columns(df)
    for name, df in datasets.items()
}

print(datasets["reviews"].columns.tolist())

['review_id', 'order_id', 'customer_id', 'rating', 'sentiment', 'review_date']

In [ ]:
datasets = {
    name: standardize_columns(df)
    for name, df in datasets.items()
}

print(datasets["products"].columns.tolist())

['product_id', 'product_name', 'category', 'subcategory', 'unit_price', 'cost_price']

In [ ]:
datasets = {
    name: standardize_columns(df)
    for name, df in datasets.items()
}

print(datasets["payments"].columns.tolist())

['payment_id', 'order_id', 'payment_method', 'payment_amount', 'payment_status']

In [ ]:
datasets = {
    name: standardize_columns(df)
    for name, df in datasets.items()
}

print(datasets["order_items"].columns.tolist())

['order_id', 'order_item_id', 'product_id', 'seller_id', 'quantity', 'selling_price', 'discount_percent', 'item_revenue', 'freight_value']

In [ ]:
datasets = {
    name: standardize_columns(df)
    for name, df in datasets.items()
}

print(datasets["analytics"].columns.tolist())

['order_id', 'order_date', 'order_status', 'customer_id', 'gender', 'city', 'state', 'product_id', 'product_name', 'category', 'subcategory', 'quantity', 'selling_price', 'discount_percent', 'revenue', 'profit', 'freight_value', 'seller_id', 'seller_status_ref', 'seller_rating', 'delivery_days']

# **11. Identifying The Data Types**

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving customers.csv to customers (2).csv

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving order_items.csv to order_items (1).csv

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving orders.csv to orders (1).csv

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving payments.csv to payments (1).csv

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving products.csv to products (1).csv

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving reviews.csv to reviews (1).csv

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving sellers.csv to sellers (1).csv

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving analytics_cleaned.csv to analytics_cleaned (3).csv

In [ ]:

import pandas as pd
from pathlib import Path

# Folder containing your uploaded CSV files
DATA_DIR = Path("/content")
OUTPUT_DIR = DATA_DIR / "typed_data"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# All 8 datasets: none are optional
file_names = {
    "Customers": "customers.csv",
    "Products": "products.csv",
    "Sellers": "sellers.csv",
    "Orders": "orders.csv",
    "Order_Items": "order_items.csv",
    "Payments": "payments.csv",
    "Reviews": "reviews.csv",
    "Analytics": "analytics_cleaned.csv"
}

# Identifier columns: keep as text
id_columns = [
    "customer_id", "product_id", "seller_id",
    "order_id", "order_item_id", "payment_id",
    "review_id", "event_id", "transaction_id"
]

# Date and timestamp columns
date_columns = [
    "order_date", "registration_date", "payment_date",
    "review_date", "event_date", "event_timestamp",
    "timestamp", "created_at", "updated_at"
]

# Numeric columns
numeric_columns = [
    "price", "unit_price", "subtotal", "total_amount",
    "amount", "revenue", "discount", "tax",
    "shipping_cost", "rating", "quantity",
    "stock_quantity", "inventory", "age"
]

integer_columns = [
    "quantity", "stock_quantity", "inventory", "age", "rating"
]

# Verify all required files exist before processing
missing_files = [
    filename for filename in file_names.values()
    if not (DATA_DIR / filename).is_file()
]

if missing_files:
    raise FileNotFoundError(
        "Upload or rename these required files first:\n"
        + "\n".join(missing_files)
    )

typed_datasets = {}
type_reports = []

# Process every dataset
for dataset_name, filename in file_names.items():

    print(f"\nProcessing {dataset_name}...")

    # Read all columns as strings initially to preserve IDs
    df = pd.read_csv(
        DATA_DIR / filename,
        dtype="string",
        keep_default_na=False
    )

    # Standardize column names
    df.columns = (
        df.columns.str.strip()
        .str.lower()
        .str.replace(r"[^a-z0-9]+", "_", regex=True)
        .str.strip("_")
    )

    # Standardize blank cells to missing values
    df = df.replace(r"^\s*$", pd.NA, regex=True)

    # Trim spaces in text fields
    for col in df.select_dtypes(
        include=["object", "string"]
    ).columns:
        df[col] = df[col].str.strip()

    # Convert ID columns to string
    for col in id_columns:
        if col in df.columns:
            df[col] = df[col].astype("string")

    # Convert date and timestamp columns
    for col in date_columns:
        if col in df.columns:
            cleaned = df[col].replace(
                ["N/A", "NA", "null", "None", ""], pd.NA
            )
            df[col] = pd.to_datetime(
                cleaned, errors="coerce"
            )

    # Convert numeric fields
    for col in numeric_columns:
        if col in df.columns:
            cleaned = df[col].replace(
                ["N/A", "NA", "null", "None", ""], pd.NA
            )
            numeric = pd.to_numeric(
                cleaned, errors="coerce"
            )

            if col in integer_columns:
                df[col] = numeric.astype("Int64")
            else:
                df[col] = numeric

    # Save the converted dataset
    output_path = OUTPUT_DIR / f"{dataset_name.lower()}_typed.csv"
    df.to_csv(output_path, index=False)

    typed_datasets[dataset_name] = df

    # Record resulting data types
    for col in df.columns:
        type_reports.append({
            "Dataset": dataset_name,
            "Column": col,
            "Data_Type": str(df[col].dtype)
        })

    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("Saved:", output_path)
    print(df.dtypes.to_string())

# Save a single report for all 8 datasets
type_report = pd.DataFrame(type_reports)
type_report.to_csv(
    OUTPUT_DIR / "all_datasets_data_types.csv",
    index=False
)

print("\nAll 8 datasets processed successfully.")
print("Data type report saved.")
display(type_report)

Processing Customers...
Rows: 300
Columns: 7
Saved: /content/typed_data/customers_typed.csv
customer_id          string[python]
customer_name        string[python]
gender               string[python]
age                           Int64
city                 string[python]
state                string[python]
registration_date    datetime64[ns]

Processing Products...
Rows: 100
Columns: 6
Saved: /content/typed_data/products_typed.csv
product_id      string[python]
product_name    string[python]
category        string[python]
subcategory     string[python]
unit_price             Float64
cost_price      string[python]

Processing Sellers...
Rows: 40
Columns: 5
Saved: /content/typed_data/sellers_typed.csv
seller_id        string[python]
seller_name      string[python]
city             string[python]
state            string[python]
seller_rating    string[python]

Processing Orders...
Rows: 2000
Columns: 6
Saved: /content/typed_data/orders_typed.csv
order_id          string[python]
customer_id       string[python]
order_date        datetime64[ns]
order_status      string[python]
payment_method    string[python]
shipping_state    string[python]

Processing Order_Items...
Rows: 2857
Columns: 9
Saved: /content/typed_data/order_items_typed.csv
order_id            string[python]
order_item_id       string[python]
product_id          string[python]
seller_id           string[python]
quantity                     Int64
selling_price       string[python]
discount_percent    string[python]
item_revenue        string[python]
freight_value       string[python]

Processing Payments...
Rows: 2000
Columns: 5
Saved: /content/typed_data/payments_typed.csv
payment_id        string[python]
order_id          string[python]
payment_method    string[python]
payment_amount    string[python]
payment_status    string[python]

Processing Reviews...
Rows: 1452
Columns: 6
Saved: /content/typed_data/reviews_typed.csv
review_id      string[python]
order_id       string[python]
customer_id    string[python]
rating                  Int64
sentiment      string[python]
review_date    datetime64[ns]

Processing Analytics...
Rows: 2857
Columns: 21
Saved: /content/typed_data/analytics_typed.csv
order_id             string[python]
order_date           datetime64[ns]
order_status         string[python]
customer_id          string[python]
gender               string[python]
city                 string[python]
state                string[python]
product_id           string[python]
product_name         string[python]
category             string[python]
subcategory          string[python]
quantity                      Int64
selling_price        string[python]
discount_percent     string[python]
revenue                     Float64
profit               string[python]
freight_value        string[python]
seller_id            string[python]
seller_status_ref    string[python]
seller_rating        string[python]
delivery_days        string[python]

All 8 datasets processed successfully.
Data type report saved.

      Dataset             Column Data_Type
0   Customers        customer_id    string
1   Customers      customer_name    string
2   Customers             gender    string
3   Customers                age     Int64
4   Customers               city    string
..        ...                ...       ...
60  Analytics      freight_value    string
61  Analytics          seller_id    string
62  Analytics  seller_status_ref    string
63  Analytics      seller_rating    string
64  Analytics      delivery_days    string

[65 rows x 3 columns]

# **12. Checking The Relationships Between Datasets**

In [ ]:

import pandas as pd
from pathlib import Path

# 1. Load all CSV datasets from Colab
DATA_DIR = Path("/content")

datasets = {}

for file in DATA_DIR.glob("*.csv"):
    name = file.stem.lower().replace(" ", "_")

    # Skip output files created during earlier cleaning
    if name.endswith("_cleaned"):
        continue

    # Standardize dataset names
    name = name.replace("-", "_")
    datasets[name] = pd.read_csv(file, dtype="string")

# 2. Standardize column names and values
for name, df in datasets.items():
    df.columns = (
        df.columns.str.strip()
        .str.lower()
        .str.replace(r"[^a-z0-9]+", "_", regex=True)
        .str.strip("_")
    )

    for col in df.select_dtypes(
        include=["object", "string"]
    ).columns:
        df[col] = df[col].str.strip()

print("Datasets found:", list(datasets.keys()))


# 3. Find a dataset using possible filename variations
def get_dataset(name):
    for key, df in datasets.items():
        if key == name or key.startswith(name + "_"):
            return df
    return None


# 4. Define primary keys to check
primary_keys = {
    "customers": ["customer_id"],
    "products": ["product_id"],
    "sellers": ["seller_id"],
    "orders": ["order_id"],
    "order_items": ["order_item_id"],
    "payments": ["payment_id"],
    "reviews": ["review_id"],
}

print("\n========== PRIMARY KEY CHECKS ==========")

for table, columns in primary_keys.items():
    df = get_dataset(table)

    if df is None:
        print(f"{table}: Dataset not found")
        continue

    for col in columns:
        if col not in df.columns:
            print(f"{table}: Column '{col}' not found")
            continue

        ids = df[col].dropna()
        ids = ids[~ids.str.lower().isin(["", "n/a", "nan", "null"])]

        duplicates = ids[ids.duplicated(keep=False)]

        print(
            f"{table}.{col}: "
            f"{len(duplicates)} rows with duplicate IDs; "
            f"{df[col].isna().sum()} missing IDs"
        )


# 5. Define foreign key relationships
relationships = [
    ("orders", "customer_id", "customers", "customer_id"),
    ("order_items", "order_id", "orders", "order_id"),
    ("order_items", "product_id", "products", "product_id"),
    ("order_items", "seller_id", "sellers", "seller_id"),
    ("payments", "order_id", "orders", "order_id"),
    ("reviews", "order_id", "orders", "order_id"),
    ("reviews", "customer_id", "customers", "customer_id"),
    ("reviews", "product_id", "products", "product_id"),
    ("analytics", "order_id", "orders", "order_id"),
    ("analytics", "customer_id", "customers", "customer_id"),
    ("analytics", "product_id", "products", "product_id"),
    ("analytics", "seller_id", "sellers", "seller_id"),
    ("products", "seller_id", "sellers", "seller_id"),
]

print("\n========== FOREIGN KEY CHECKS ==========")

results = []

missing_tokens = ["", "n/a", "nan", "null", "none", "<na>"]

for child_table, child_col, parent_table, parent_col in relationships:
    child = get_dataset(child_table)
    parent = get_dataset(parent_table)

    # Skip relationships whose datasets or columns do not exist
    if child is None or parent is None:
        continue

    if child_col not in child.columns or parent_col not in parent.columns:
        continue

    child_ids = child[child_col].astype("string").str.strip()
    parent_ids = parent[parent_col].astype("string").str.strip()

    # Exclude missing/placeholder references from orphan checks
    valid_child = child_ids[
        child_ids.notna()
        & ~child_ids.str.lower().isin(missing_tokens)
    ]

    valid_parent = parent_ids[
        parent_ids.notna()
        & ~parent_ids.str.lower().isin(missing_tokens)
    ]

    parent_set = set(valid_parent)

    orphan_mask = ~valid_child.isin(parent_set)
    orphan_count = int(orphan_mask.sum())
    missing_count = int(
        (child_ids.isna()
         | child_ids.str.lower().isin(missing_tokens)).sum()
    )

    results.append({
        "relationship": (
            f"{child_table}.{child_col} -> "
            f"{parent_table}.{parent_col}"
        ),
        "orphan_references": orphan_count,
        "missing_references": missing_count,
        "status": "CHECK REQUIRED" if orphan_count else "PASS"
    })

    print(
        f"{child_table}.{child_col} -> "
        f"{parent_table}.{parent_col}: "
        f"{orphan_count} orphan references, "
        f"{missing_count} missing references"
    )

# 6. Save the relationship validation report
if results:
    report = pd.DataFrame(results)
    report.to_csv(
        "/content/relationship_validation_report.csv",
        index=False
    )

    print("\n========== SUMMARY ==========")
    display(report)

    print("Report saved as relationship_validation_report.csv")
else:
    print(
        "No relationships were checked. "
        "Verify dataset filenames and column names."
    )

Datasets found: ['customers_(1)', 'analytics_cleaned_(1)', 'sellers', 'orders_(1)', 'analytics_(1)', 'customers', 'analytics_cleaned_(3)', 'order_items_(1)', 'reviews_(1)', 'analytics_quality_report', 'analytics_cleaned_(2)', 'customers_(2)', 'sellers_(1)', 'products', 'products_(1)', 'analytics', 'reviews', 'payments_(1)', 'data_quality_report', 'payments', 'relationship_validation_report', 'orders', 'order_items']

========== PRIMARY KEY CHECKS ==========
customers.customer_id: 0 rows with duplicate IDs; 0 missing IDs
products.product_id: 0 rows with duplicate IDs; 0 missing IDs
sellers.seller_id: 0 rows with duplicate IDs; 0 missing IDs
orders.order_id: 0 rows with duplicate IDs; 0 missing IDs
order_items.order_item_id: 2857 rows with duplicate IDs; 0 missing IDs
payments.payment_id: 0 rows with duplicate IDs; 0 missing IDs
reviews.review_id: 0 rows with duplicate IDs; 0 missing IDs

========== FOREIGN KEY CHECKS ==========
orders.customer_id -> customers.customer_id: 0 orphan references, 0 missing references
order_items.order_id -> orders.order_id: 0 orphan references, 0 missing references
order_items.product_id -> products.product_id: 0 orphan references, 0 missing references
order_items.seller_id -> sellers.seller_id: 0 orphan references, 0 missing references
payments.order_id -> orders.order_id: 0 orphan references, 0 missing references
reviews.order_id -> orders.order_id: 0 orphan references, 0 missing references
reviews.customer_id -> customers.customer_id: 0 orphan references, 0 missing references
analytics.order_id -> orders.order_id: 0 orphan references, 0 missing references
analytics.customer_id -> customers.customer_id: 0 orphan references, 0 missing references
analytics.product_id -> products.product_id: 0 orphan references, 0 missing references
analytics.seller_id -> sellers.seller_id: 0 orphan references, 0 missing references

========== SUMMARY ==========

,relationship,orphan_references,missing_references,status
0,orders.customer_id -> customers.customer_id,0,0,PASS
1,order_items.order_id -> orders.order_id,0,0,PASS
2,order_items.product_id -> products.product_id,0,0,PASS
3,order_items.seller_id -> sellers.seller_id,0,0,PASS
4,payments.order_id -> orders.order_id,0,0,PASS
5,reviews.order_id -> orders.order_id,0,0,PASS
6,reviews.customer_id -> customers.customer_id,0,0,PASS
7,analytics.order_id -> orders.order_id,0,0,PASS
8,analytics.customer_id -> customers.customer_id,0,0,PASS
9,analytics.product_id -> products.product_id,0,0,PASS
10,analytics.seller_id -> sellers.seller_id,0,0,PASS

Report saved as relationship_validation_report.csv

# **13. Final Quality Check Report**

In [ ]:
analytics_df = analytics_df.fillna("N/A")

analytics_df.to_csv(
    "/content/analytics_cleaned.csv",
    index=False
)

In [ ]:
import pandas as pd

analytics_df = pd.read_csv(
    "/content/analytics_cleaned.csv",
    keep_default_na=False
)

print("Missing cells:", analytics_df.isna().sum().sum())
print("N/A cells:", (analytics_df == "N/A").sum().sum())

Missing cells: 0
N/A cells: 714

In [ ]:
# STEP 10: QUALITY CHECK FOR CLEANED ANALYTICS DATASET

import pandas as pd
import os

# Load the latest cleaned Analytics dataset
file_path = "/content/analytics_cleaned.csv"

if not os.path.exists(file_path):
    raise FileNotFoundError(
        "analytics_cleaned.csv not found. Please upload the latest cleaned file."
    )

analytics_df = pd.read_csv(file_path, keep_default_na=False)

print("=" * 60)
print("ANALYTICS DATASET - DATA QUALITY REPORT")
print("=" * 60)

# 1. Dataset dimensions
print("\n1. DATASET SIZE")
print("Number of rows:", analytics_df.shape[0])
print("Number of columns:", analytics_df.shape[1])

# 2. Column names and data types
print("\n2. COLUMN NAMES AND DATA TYPES")
print(analytics_df.dtypes)

# 3. Missing values
print("\n3. MISSING VALUES PER COLUMN")
missing_values = analytics_df.isna().sum()

# Also count blank cells
blank_values = analytics_df.apply(
    lambda col: col.astype("string").str.strip().eq("").sum()
)

# Count common missing-value markers
missing_markers = analytics_df.apply(
    lambda col: col.astype("string").str.strip().str.upper()
    .isin(["N/A", "NA", "NULL", "NONE"]).sum()
)

quality_report = pd.DataFrame({
    "Missing Values": missing_values,
    "Blank Values": blank_values,
    "N/A or NULL Markers": missing_markers
})

display(quality_report)

# 4. Total missing and blank cells
print("\n4. TOTAL QUALITY COUNTS")
print("Pandas missing cells:", int(missing_values.sum()))
print("Blank cells:", int(blank_values.sum()))
print("Missing-value marker cells:", int(missing_markers.sum()))

# 5. Duplicate records
print("\n5. DUPLICATE RECORDS")
print("Total duplicate rows:", analytics_df.duplicated().sum())

# 6. Duplicate column names
print("\n6. DUPLICATE COLUMN NAMES")
duplicate_columns = analytics_df.columns[
    analytics_df.columns.duplicated()
].tolist()
print(duplicate_columns if duplicate_columns else "None")

# 8. Save the quality report
report_path = "/content/analytics_quality_report.csv"
quality_report.to_csv(report_path)

print("\nQuality report saved to:", report_path)
print("\nQUALITY CHECK COMPLETED")

============================================================
ANALYTICS DATASET - DATA QUALITY REPORT
============================================================

1. DATASET SIZE
Number of rows: 2857
Number of columns: 21

2. COLUMN NAMES AND DATA TYPES
order_id              object
order_date            object
order_status          object
customer_id           object
gender                object
city                  object
state                 object
product_id            object
product_name          object
category              object
subcategory           object
quantity               int64
selling_price        float64
discount_percent       int64
revenue              float64
profit               float64
freight_value        float64
seller_id             object
seller_status_ref     object
seller_rating        float64
delivery_days         object
dtype: object

3. MISSING VALUES PER COLUMN

                   Missing Values  Blank Values  N/A or NULL Markers
order_id                        0             0                    0
order_date                      0             0                    0
order_status                    0             0                    0
customer_id                     0             0                    0
gender                          0             0                    0
city                            0             0                    0
state                           0             0                    0
product_id                      0             0                    0
product_name                    0             0                    0
category                        0             0                    0
subcategory                     0             0                    0
quantity                        0             0                    0
selling_price                   0             0                    0
discount_percent                0             0                    0
revenue                         0             0                    0
profit                          0             0                    0
freight_value                   0             0                    0
seller_id                       0             0                    0
seller_status_ref               0             0                    0
seller_rating                   0             0                    0
delivery_days                   0             0                  714

4. TOTAL QUALITY COUNTS
Pandas missing cells: 0
Blank cells: 0
Missing-value marker cells: 714

5. DUPLICATE RECORDS
Total duplicate rows: 0

6. DUPLICATE COLUMN NAMES
None

Quality report saved to: /content/analytics_quality_report.csv

QUALITY CHECK COMPLETED